kind: pipeline
name: default
clone:
  disable: true

steps:
- name: clone
  image: drone/git
  extra_hosts:
    - "gitlab.matosiki.cn:192.168.51.240"

- name: test
  image: golang:1.12
  extra_hosts:
    - "gitlab.matosiki.cn:192.168.51.240"
  commands:
  - go test ./...

